### ISSUE TITLE
quantisation aware training flow

### ISSUE THREAD

**Issue by widmerl** [ZLkanyo009/STBP-train-and-compression#1]
Hi!

As far as I can tell, you are doing the following during training: 
Training loop (over batches):
    Forward pass.
    Backward pass
    Update weights
    Quantize weights

This means that you always have the forward pass on quantized weights, and can calculate the backward pass and weight update as usual.
I think that this is possibly problematic though, because small updates on the weights always get reset to the closest quantized value, and have no chance to accumulate over multiple passes to get to the next value. Is this the case? Or am I missing something?

**Comment by ZLkanyo009** [comment]
Hello. The normal process should be: we first train an unquantified SNN (fp32), and then use its weight for quantize aware training,  as you said above.

**Comment by widmerl** [comment]
I see, but does that not also suffer from the issue with small weight updates getting lost that I mentioned above?

**Comment by ZLkanyo009** [comment]
You're right. Maybe I should update the fp32 weight directly during the backward propagation, rather than the quantified weight. I will update the version later. However, Surprisingly, updating the weight of int8 can indeed improve the network accuracy, rather than not updating the weight all the time.

**Comment by ZLkanyo009** [comment]
Hi, I fix this problem now.You can check the code.

**Comment by widmerl** [comment]
That looks good!
